pre_app_deploy:
 execs:
  Get mediawiki source:
   name: Get mediawiki source
   command: |
     wget -qO- https://releases.wikimedia.org/mediawiki/1.30/mediawiki-1.30.0.tar.gz | tar xvz  -C . --strip 1

post_app_deploy:
 execs:
  Restart apache:
   name: Restart apache
   command: |
     #!/usr/bin/env bash
     chown -RL www-data:www-data <%= @app_root %>
     service apache2 restart
